<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="26081" started-at="2021-02-03T11:04:06Z" finished-at="2021-02-03T11:04:32Z">
    <groups>
    </groups>
    <test name="Navigation Bars" duration-ms="26081" started-at="2021-02-03T11:04:06Z" finished-at="2021-02-03T11:04:32Z">
      <class name="Academy.ValidateTitle_NavigationBar">
        <test-method status="PASS" signature="Initialize()[pri:0, instance:Academy.ValidateTitle_NavigationBar@8458f04]" name="Initialize" is-config="true" duration-ms="7064" started-at="2021-02-03T11:04:06Z" finished-at="2021-02-03T11:04:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initialize -->
        <test-method status="FAIL" signature="getTitle()[pri:0, instance:Academy.ValidateTitle_NavigationBar@8458f04]" name="getTitle" duration-ms="16062" started-at="2021-02-03T11:04:13Z" finished-at="2021-02-03T11:04:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at Academy.ValidateTitle_NavigationBar.getTitle(ValidateTitle_NavigationBar.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Academy.ValidateTitle_NavigationBar@8458f04]" name="tearDown" is-config="true" duration-ms="1310" started-at="2021-02-03T11:04:31Z" finished-at="2021-02-03T11:04:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Academy.ValidateTitle_NavigationBar -->
    </test> <!-- Navigation Bars -->
  </suite> <!-- Suite -->
</testng-results>
